version: '3.7'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
        - "8000:8000"
        depends_on:
        - db

    # PostgreSQL database
    db:
        image: postgres:latest
        environment:
        - POSTGRES_PASSWORD=a
        - POSTGRES_USER=postgres
        - POSTGRES_DB=as-planned
        volumes:
        - ./db:/var/lib/postgresql/data
